---
abstract: 'Log::Log4perl logging for Catalyst'
author:
  - 'Adam Jacob, C<adam@stalecoffee.org>'
distribution_type: module
generated_by: 'Module::Install version 0.80'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Catalyst-Log-Log4perl
no_index:
  directory:
    - inc
    - t
requires:
  Catalyst: 5.60
  Data::Dump: 0
  Log::Log4perl: 0.49
  MRO::Compat: 0
  Params::Validate: 0
  Sub::Install: 0
resources:
  license: http://dev.perl.org/licenses/
version: 1.03
