abstract: Log::Log4perl logging for Catalyst
author: Adam Jacob, C<adam@stalecoffee.org>
distribution_type: module
generated_by: Module::Install version 0.64
license: perl
name: Catalyst-Log-Log4perl
no_index: 
  directory: 
    - inc
    - t
requires: 
  Catalyst: 5.60
  Log::Log4perl: 0.49
  Params::Validate: 0
  Sub::Install: 0
version: 0.51
